remote_theme: pages-themes/cayman
plugins:
- jekyll-remote-theme
title: Sports Analytics Challenge - Spring 2022
description: Kenyon Sports Analytics Society | NHL Skaters Data | 2021-22 Season
baseurl: /nhlskaters
